elm.js: src/*.elm src/**/*.elm src/Native/*.js
	elm-make src/Main.elm

gh-pages:
	$(eval sha = $(shell git rev-parse HEAD))
	git checkout --detach --quiet
	git symbolic-ref HEAD refs/heads/gh-pages
	$(MAKE) elm.js
	git checkout gh-pages -- .gitignore
	git rm -r --force --quiet --cached .
	git add .
	git commit --quiet --amend -m 'Build $(sha)'$$'\n\n''This branch should not have any history. It is automatically generated by the gh-pages target of the makefile on the master branch.'
	git checkout -
	$(MAKE) elm.js

publish: gh-pages
	git push origin gh-pages --force

.PHONY: gh-pages publish
